@startuml
autonumber

participant "Người dùng" as User
participant "App (Frontend)" as App
participant "Auth Controller" as Controller
participant "User Model" as Model
database "MySQL" as DB

== Đăng nhập ==

User -> App : Nhập Username/Password
App -> Controller : POST /api/login
Controller -> Model : findOne({username})
Model -> DB : Query User
DB --> Model : Record User
Model --> Controller : Object User (gồm hash)

alt [User không tồn tại]
    Controller -> App : Trả về lỗi 401
else [Mật khẩu sai]
    Controller -> Model : validPassword()
    Model -> Model : bcrypt.compare()
    Model --> Controller : false
    Controller -> App : Trả về lỗi 401
else [Xác thực thành công]
    Controller -> Controller : jwt.sign()
    Controller -> App : Trả về Token
    App -> User : Vào Home
end
@enduml
