@startuml
autonumber

participant "User App" as U
participant "Socket Server" as S
database "MySQL (ChatMessages)" as DB
participant "Admin Web" as A

== Khởi tạo ==
U -> S : join_room (userId)
S -> S : Gán phòng chat

== Gửi tin nhắn (User -> Admin) ==
U -> S : emit('send_message')
S -> DB : INSERT ChatMessages
S -> A : emit('new_message')
A -> A : Hiện tin nhắn

== Admin phản hồi ==
A -> S : emit('send_message')
S -> DB : INSERT ChatMessages
S -> U : emit('receive_message')
U -> U : Hiện tin nhắn
@enduml
